### ISSUE TITLE
Edit times after the fact

### ISSUE THREAD

**Issue by MaineC** [t-lo/schnarchinator#2]
I sometimes (especially at day time at home) forget entering the correct times through the buttons. As for me the only goal is to track times approximately it would be great to be able to enter additional times/events through the browser whenever I have time.

Some simple editing window that lists the existing times and allows for adding more would be sufficient.

**Comment by t-lo** [comment]
Implemented in 8a2c073808b0437e530615638b6a2fcce0cabe3b, please verify.

**Comment by MaineC** [comment]
Works
